version: '3.8'

services:
  db:
    # 修正点: build: . を指定し、上記のDockerfileを使ってイメージを構築する
    build: . 
    container_name: postgres_todo
    restart: always 
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'todo_app'
      # Dockerfileで設定したので、環境変数はDB名と認証情報に絞る
    
volumes:
  db-store: